<a href="https://colab.research.google.com/github/sakshu2810/Combined-cycle-power-plant/blob/main/Combined_cycle_power_plant.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Artificial Neural Network**

# Importing the libraries

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf


In [3]:
tf.__version__

'2.6.0'

# Part 1 - Data Preprocessing

# Importing the dataset

In [12]:
dataset = pd.read_csv('/content/Folds5x2_pp.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [10]:
print(X)

[[   8.34   40.77 1010.84   90.01]
 [  23.64   58.49 1011.4    74.2 ]
 [  29.74   56.9  1007.15   41.91]
 ...
 [  15.99   43.34 1014.2    78.66]
 [  17.65   59.87 1018.58   94.65]
 [  23.68   51.3  1011.86   71.24]]


In [13]:
print(y)

[480.48 445.75 438.76 ... 465.96 450.93 451.67]


# Splitting the dataset into the Training set and Test set

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Part 2 - Building the ANN

# Initializing the ANN

In [17]:
ann = tf.keras.models.Sequential()

# Adding the input layer and the first hidden layer

In [18]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the second hidden layer

In [19]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the output layer

In [20]:
ann.add(tf.keras.layers.Dense(units=1))

# Part 3 - Training the ANN

# Compiling the ANN

In [21]:
ann.compile(optimizer='adam', loss='mean_squared_error')

# Training the ANN model on the Training set

In [24]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
240/240 [==============================] - 0s 1ms/step - loss: 26.6322
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 26.8050
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 26.6018
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 26.9893
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 26.4253
Epoch 6/100
240/240 [==============================] - 0s 993us/step - loss: 26.3711
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 26.4814
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 26.4590
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 26.3113
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 26.9615
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 26.7559
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - loss: 26.6841

# Predicting the results of the Test set

In [23]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


[[429.4  426.18]
 [448.79 451.1 ]
 [444.26 442.87]
 ...
 [455.31 454.2 ]
 [448.29 444.13]
 [430.57 436.58]]
